import {Card, CardContent, CardDescription, CardHeader, CardTitle} from "@/components/ui/card.tsx";
import {SlidersHorizontal} from "lucide-react";
import {Table, TableBody, TableCell, TableHead, TableHeader, TableRow} from "@/components/ui/table.tsx";
import type {TestingResultsCardProps} from "@/types/props/TestingResultsCardProps.ts";
import React from "react";
import getHookDefaultValues from "@/constants/getHookDefaultValues.ts";

const TestingResultsCard = (
    {
        testingConfigureInputWeightsHookProps,
        testingResultsHookProps,
        testingLowerTriggerMessageHookProps,
        testingHigherTriggerMessageHookProps,
    }: TestingResultsCardProps ) => {

    const { testingConfigureInputWeight: testingConfigureInputWeightDefaultValue } = getHookDefaultValues()

    return (
        <Card className="w-full">
            <CardHeader>
                <CardTitle className="flex flex-row items-center gap-2">
                    <SlidersHorizontal size="18"/>
                    Test Results
                </CardTitle>
                <CardDescription>
                    Review the predictions generated by your trained neuron for each test case.
                </CardDescription>
            </CardHeader>
            <CardContent className="flex flex-col gap-4">
                <div className="flex flex-col gap-4">
                    <Card className="w-full" size="sm">
                        <CardHeader>
                            <CardTitle>Test Cases</CardTitle>
                            <CardDescription>Below is a detailed breakdown of inputs, activation outputs, and corresponding predictions.</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="h-70 lg:h-80 max-h-70 lg:max-h-80 overflow-auto">
                                <Table>
                                    <TableHeader>
                                        <TableRow>
                                            <TableHead>#.</TableHead>
                                            {testingConfigureInputWeightsHookProps.testingConfigureInputWeights.length < 1 ? (
                                                <TableHead>Input</TableHead>
                                            ) : testingConfigureInputWeightsHookProps.testingConfigureInputWeights.map((testingConfigureInputWeight, index) => (
                                                <TableHead key={testingConfigureInputWeight.id} className="capitalize">{testingConfigureInputWeight.label.length > 0 && testingConfigureInputWeight.label !== testingConfigureInputWeightDefaultValue.label ? (testingConfigureInputWeight.label) : (`Input ${index + 1}`)}</TableHead>
                                            ))}
                                            <TableHead>Activation</TableHead>
                                            <TableHead>Prediction</TableHead>
                                        </TableRow>
                                    </TableHeader>
                                    <TableBody>
                                        {testingResultsHookProps.testingResults.length < 1 ? (
                                            <TableRow>
                                                <TableCell colSpan={(testingConfigureInputWeightsHookProps.testingConfigureInputWeights.length < 1 ? 1 : testingConfigureInputWeightsHookProps.testingConfigureInputWeights.length) + 3} className="text-center py-26 lg:py-30 text-muted-foreground">No Results</TableCell>
                                            </TableRow>
                                        ) : (testingResultsHookProps.testingResults.map((testingResults, index) => (
                                            <TableRow key={index}>
                                                <TableCell className="font-medium">{index + 1}.</TableCell>
                                                {testingResults.map((testingResult, index) =>
                                                    index < (testingResults.length - 1) ? (
                                                        <TableCell
                                                            className="font-medium"
                                                            key={index}
                                                        >
                                                            {testingResult}
                                                        </TableCell>
                                                    ) : testingResult < 0.5 ? (
                                                        <React.Fragment key={index}>
                                                            <TableCell className="font-medium">{testingResult}</TableCell>
                                                            <TableCell className="font-medium">{testingLowerTriggerMessageHookProps.testingLowerTriggerMessage}</TableCell>
                                                        </React.Fragment>
                                                    ) : (
                                                        <React.Fragment key={index}>
                                                            <TableCell className="font-medium">{testingResult}</TableCell>
                                                            <TableCell className="font-medium">{testingHigherTriggerMessageHookProps.testingHigherTriggerMessage}</TableCell>
                                                        </React.Fragment>
                                                    )
                                                )}
                                            </TableRow>
                                        )))}
                                    </TableBody>
                                </Table>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </CardContent>
        </Card>
    )
}

export default TestingResultsCard